### PR TITLE
Add new full Sublime color schemes.

### PR DESCRIPTION
**Pull request by crhallberg**
Use the updated `.sublime-color-scheme` format, matching the colors and the [theme specification](https://rosepinetheme.com/docs/usage). I had a blast doing this! Happy Hacktoberfest!

**Notes**

1. Keys (Foam) isn't used, probably through an oversight on my part.
1. I recommend changing the active line background Overlay for better contrast.
1. I recommend changing the Ruler and Active Guide color Muted for contrast.
1. If used in conjunction with a full Rosé Pine Sublime theme, I would recommend Base for the Sublime interface background, Surface for the editor background, and Overlay for the gutter.

I'd also like to start a full [Sublime theme](https://www.sublimetext.com/docs/themes.html) to match the full interface, but that's another PR.

### CODE REVIEW

**Comment by mvllow** [comment]
This is lovely, thanks so much for the hard work!

> 2. I recommend changing the active line background Overlay for better contrast.
> 3. I recommend changing the Ruler and Active Guide color Muted for contrast.

Are these recommendations currently implemented? If not, I'm all for better contrast and approve of those changes if you do as well :)

If I'm not mistaken, our current theme is one variant and also just syntax so perhaps this should replace that.

_Maybe @fvrests would like to test this out as well and give any feedback more specific to the theme, if any._

**Comment by crhallberg** [comment]
I did not implement these suggestions, I chose to keep the scheme in line with the documentation. I can make these changes easily, along with any other feedback!

I don't have enough information to decide on removing the current `.tmTheme`. It depends on how many users are still using Sublime Text 3, which doesn't support the new format.

**Comment by piuvas** [comment]
I've adapted the original ThTheme (TextMate) file to the new palette for my own personal project and then found this PR. If you're interested, I've uploaded it here: [24 hour timed link](https://wormhole.app/MOKd6#MKLeqjQSl4ofvo3HhFEo2Q).

**Comment by fvrests** [comment]
Thanks for the wonderful contribution! It's great to have updated support for Sublime Text.

> 1. Keys (Foam) isn't used, probably through an oversight on my part.

Not sure if this is what you were thinking of, but the below scope should theme JSON keys. 

```
        {
            "name": "JSON keys",
            "scope": "meta.mapping.key.json string,meta.structure.dictionary.key.json string",
            "foreground": "var(foam)"
        },
```

> 2. I recommend changing the active line background Overlay for better contrast.
> 3. I recommend changing the Ruler and Active Guide color Muted for contrast.

Love the increased contrast / usability, go ahead and update if you are still willing.

> I would recommend Base for the Sublime interface background, Surface for the editor background, and Overlay for the gutter.

I believe `base` as editor background & gutter would be more in line with the spec & existing apps, erring on the side of lesser visual hierarchy for a more "zen-like" experience. I'd worry a bit about text contrast on the other two colors, as some text colors are already quite dim on `base`. Would love to see a PR on UI in the future!

**Comment by crhallberg** [comment]
More than happy to make these changes! And I used the theme with Surface for a few weeks before tweaking for this PR, so I can attest to the contrast. I'll have more commits soon!

**Pull request merged**
