### PR TITLE
update filenames

### PR DESCRIPTION
**Pull request by braver**
1. ~Looking at other editor implementations, the background should use the surface color, not base. Base seems to be intended for the UI "frame" elements, e.g. gutter. This also improves contrast in the light color scheme.~

2. Rename the templates so that they're listed correctly in the command palette (see screenshots).

before:
Scherm­afbeelding 2024-03-09 om 16 35 38

after:
Scherm­afbeelding 2024-03-09 om 16 48 03

3. Some minor cleanup to improve the package for publishing.

I would like to publish this color scheme in [Package Control](https://packagecontrol.io) so that more users of Sublime Text can find it easily. I could also help finish that UI theme work. If possible, maybe allow me to collaborate on this project? For reference, I maintain [several packages](https://packagecontrol.io/search/braver) for Sublime Text, as well as the Package Control listing itself.

### CODE REVIEW

**Comment by mvllow** [comment]
I appreciate the rename and would love to add you as a collaborator. I don't agree with having surface as the background, however. We have been talking about increasing contrast for dawn text and some other colours—happy to share the wip palette if you'd like to try some of those values. The editor/gutter/sidebar should be base and things like the command palette should be surface (not sure if this is already the case or not).

**Comment by braver** [comment]
Right, the idea to flip them was actually to _increase_ the contrast of the Dawn theme. But indeed it decreases contrast in the darker themes. Maybe they should differ on that point?

**Comment by braver** [comment]
FYI I was also trying to match Zed’s implementation of these themes, which is where I encountered them first. And they definitely use surface as the background in the lighter themes.

**Comment by mvllow** [comment]
> Right, the idea to flip them was actually to _increase_ the contrast of the Dawn theme. But indeed it decreases contrast in the darker themes. Maybe they should differ on that point?

Every official theme (should) maintain the same colour between variants. Here's the (unofficial) palette for dawn text colours that we've been toying with to increase contrast:

```
muted #736D83
subtle #6E6986
text #4E4E74
```

Surface was intentionally made lighter than base for dawn due to some colour theory—essentially dealing with perceived depth—so this is not something we would like to change.

**Comment by mvllow** [comment]
Oops, didn't mean to close.

**Comment by braver** [comment]
I went over some example implementations with the color meter and you're right (of course 😅 ). The rendered colors, or the appearance of them due to how they're combined) were off by just enough to send me off the wrong path. Corrected that now. 

Now this PR basically only changes filenames. I'd still like to move this forward and publish it, and then I could also contribute to #3? 

> I couldn't figure out how to get Sublime behave before committing.

I think I can lend a hand here 😄 

> Here's the (unofficial) palette for dawn text colours that we've been toying with to increase contrast:

That is better. I would say I prefer "muted" in the official palette, comments are more subdued then.

**Comment by mvllow** [comment]
Thank you. You now have write access to the repo :)

**Pull request merged**
