### PR TITLE
Full editor theme

### PR DESCRIPTION
**Pull request by crhallberg**
## Todo

- [ ] Double-check usage with [theme specification](https://rosepinetheme.com/docs/usage)
- [ ] Active vs. inactive editor changes background
- [ ] Hover tab still not exactly right
- [ ] Match panel inputs to docs

## Resources

- [Sublime Documentation](https://www.sublimetext.com/docs/themes.html)
- [Spacegray theme](https://github.com/SublimeText/Spacegray/blob/main/Spacegray.sublime-theme "helped me crack the code")

### CODE REVIEW

**Comment by mvllow** [comment]
I noticed you still have todos but let me know if/when this is ready for review or if any help is needed :)

**Comment by crhallberg** [comment]
Thanks! I haven't worked on this in a while. I wouldn't mind a hand on the tabs and active/inactive colors. I couldn't figure out how to get Sublime behave before committing.

**Comment by mvllow** [comment]
I tried playing around with the tabs myself and no luck :/ Maybe something is overriding those values but honestly not sure. If I have time I'll give it another shot

**Comment by kapitanluffy** [comment]
Hey guys. Awesome work you have here! Just letting you know that if you have questions with the theming, you can drop by Sublime's unofficial discord

https://discord.com/invite/D43Pecu

**Comment by braver** [comment]
closed via 0392f695d22697610ea66365443b7ca73c6b855a

**Pull request closed without merging**
